name: CD-rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Add iOS targets
      run: rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "./crate"

    - name: Build and test
      run: |
        cd ./crate/ 
        cargo c --target=aarch64-apple-ios-sim
        cargo t --target=aarch64-apple-ios-sim

    - name: Lint
      run: |
        cd ./crate/ 
        cargo clippy --target=aarch64-apple-ios-sim